### ISSUE TITLE
Not a my4th issue, instead querying how to send stellaris code contributions

### ISSUE THREAD

**Issue by Bushmills** [Mecrisp/my4th#1]
Hi Matthias,
I have a simple but useful contribution to mecrisp-stellaris core code - but as that package doesn't appear to be published on github, I wonder how to send you the closest equivalent to a pull request.
It's just a few lines, merely adding dpl to double number conversion.
What method of sharing contributed code do you prefer?

**Comment by Mecrisp** [comment]
Contributions are accepted either as E-Mail to the official address m-atthias@users.sf.net or as forum post https://sourceforge.net/p/mecrisp/discussion/general/ if you like to discuss your changes with other users.

Hey, you are the author of bashforth! I played with that some years ago. Cool project!

**Comment by Bushmills** [comment]
Indeed I am.  But today, yoda is the better bashforth. Also completely written as bash script, but compiling to bash functions rather than running a VM - and therefore much faster (or rather, "much less sluggish" :) 

But we were in contact for another matter not that long ago ... Remember the recent problem with leading bits not set with - I think - a comparison?  The person reporting this was me.  Thanks for addition to CREDITS :)
